"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote, urlparse

from decouple import Config, RepositoryEnv

BASE_DIR = Path(__file__).resolve().parent.parent

# Locally this project reads config/.env. Render has no .env file at all -
# configuration comes from the dashboard's environment variables - and
# decouple's RepositoryEnv.__init__ raises FileNotFoundError the moment the
# file is absent. Branching here is what lets the same settings file boot on
# both a laptop and a Render dyno.
_ENV_FILE = BASE_DIR / "config" / ".env"
env = (
    Config(RepositoryEnv(str(_ENV_FILE)))
    if _ENV_FILE.is_file()
    else Config(os.environ)
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False, cast=bool)

# .strip() each entry: a value like "localhost, 127.0.0.1"
# would otherwise yield a host with a leading space ->
# DisallowedHost on every request.
ALLOWED_HOSTS = [
    host.strip()
    for host in env(
        "ALLOWED_HOSTS",
        default="localhost,127.0.0.1",
    ).split(",")
    if host.strip()
]

# Django 4+ requires the scheme as well as the origin, and refuses admin
# POSTs over HTTPS without it.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in env("CSRF_TRUSTED_ORIGINS", default="").split(",")
    if origin.strip()
]

# Render terminates TLS at its router and forwards plain HTTP, tagging the
# request with X-Forwarded-Proto. Django ignores that header unless told to
# trust it - without this line request.is_secure() is always False and
# SECURE_SSL_REDIRECT bounces every visitor into an infinite redirect loop.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    "rest_framework_simplejwt.token_blacklist",
    "common",
    "medicine",
    "django_filters",
     "prescriptions",
     "ai_engine",
     "cart",
     "orders",
     "pages",
     "addresses",
     "notifications"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves STATIC_ROOT straight off the app box, so no nginx or
    # CDN is required. It must sit immediately after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Render provisions Postgres and injects DATABASE_URL automatically, so read
# that when present. Locally the DB_* values in config/.env are used.
_DATABASE_URL = env("DATABASE_URL", default="")
_DB_NAME = env("DB_NAME", default="")

if _DATABASE_URL:
    _db = urlparse(_DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            # urlparse leaves credentials percent-encoded, and Render's
            # generated passwords routinely contain characters that need it.
            "NAME": unquote((_db.path or "/").lstrip("/")),
            "USER": unquote(_db.username or ""),
            "PASSWORD": unquote(_db.password or ""),
            "HOST": _db.hostname or "",
            "PORT": str(_db.port or ""),
            "CONN_MAX_AGE": 60,
        }
    }
elif _DB_NAME:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _DB_NAME,
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST"),
            "PORT": env("DB_PORT"),
            "CONN_MAX_AGE": 60,
        }
    }
else:
    # Neither source is available. This is Render's *build* container: it
    # does not receive DATABASE_URL (Render injects that at runtime only),
    # and it has no config/.env either. The build only runs collectstatic,
    # which never touches the database - but Django still needs a
    # well-formed DATABASES dict simply to import the settings module.
    #
    # Deliberately NOT SQLite. A throwaway SQLite file would let `migrate`
    # appear to succeed while writing tables to a database nobody will ever
    # read. Empty connection values instead make any real query fail loudly
    # with a clear connection error, so a mistake here cannot pass silently.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "",
            "USER": "",
            "PASSWORD": "",
            "HOST": "",
            "PORT": "",
            "CONN_MAX_AGE": 60,
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CLOUDINARY_CLOUD_NAME = env("CLOUDINARY_CLOUD_NAME", default="")
CLOUDINARY_API_KEY = env("CLOUDINARY_API_KEY", default="")
CLOUDINARY_API_SECRET = env("CLOUDINARY_API_SECRET", default="")

# Static files always go through WhiteNoise. User uploads go to Cloudinary
# whenever this is not a local debug run, because Render's free tier has no
# persistent disk and wipes the filesystem on every deploy - a local-disk
# upload in production is a guaranteed lost prescription. Locally we keep the
# plain filesystem so no Cloudinary account is needed to develop.
STORAGES = {
    "default": {
        "BACKEND": (
            "common.cloudinary_storage.CloudinaryMediaStorage"
            if not DEBUG
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    "EXCEPTION_HANDLER": "common.exceptions.custom_exception_handler",

    # NOTE: no DEFAULT_PAGINATION_CLASS on purpose. Most list
    # endpoints (medicine, addresses, prescriptions, orders) are
    # consumed as bare JSON arrays by the frontend and there is no
    # pagination UI anywhere, so enabling it globally would break
    # them AND silently cap pages at 10 items. Opt in per-view with
    # common.pagination.DefaultPagination only where the consumer
    # already unwraps `results` (pharmacist medicines, notifications).

}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default=True, cast=bool)

EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="")
RAZORPAY_KEY_ID = env("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = env("RAZORPAY_KEY_SECRET", default="")
GEMINI_API_KEY = env("GEMINI_API_KEY", default="")
# Production security settings
if not DEBUG:
    # Default on, but env-switchable so a misconfigured proxy can be worked
    # around without editing code.
    SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT", default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # HSTS is opt-in. Once a browser has cached a long HSTS header there is no
    # practical way to undo it, so this stays off until you deliberately turn
    # it on. SECURE_HSTS_PRELOAD is intentionally never enabled.
    SECURE_HSTS_SECONDS = env("SECURE_HSTS_SECONDS", default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = False

# NOTE: SECURE_BROWSER_XSS_FILTER is gone. It was deprecated in Django 4.0 and
# removed in 5.0; modern browsers ignore X-XSS-Protection anyway.
