# Generated by Django 5.2.16 on 2026-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('medicine', '0002_medicine_is_active'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('prescription__isnull', True)), fields=('cart', 'medicine'), name='uniq_cart_medicine_no_rx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('prescription__isnull', False)), fields=('cart', 'medicine', 'prescription'), name='uniq_cart_medicine_rx'),
        ),
    ]
