# Generated by Django 5.2.16 on 2026-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
    ]
